# Example configuration for the codereview tool.
# This file should be copied to ~/.config/acre.toml

# Default commands to run when no command is specified
default_commands = "status"

[aliases]
# Example alias: `st` will be expanded to `status`
st = "status"
# If you want to get into interactive and always initialize a pull request:
i  = "interactive --auto-yes"
# Short aliases are useful for interactive mode.
lt = "ls --todo"
# Use whatever mnemonics work for you.
smol = "review --loc-lte 10"

# Include jira info to include URLs to tickets.
[jira]
base = "your-corp"
